#!/usr/bin/env python

Import('env')
Import('env_modules')

env_border_color = env_modules.Clone()

env_border_color.add_source_files(env.modules_sources, "border_color.cpp")
if env["platform"] == "macos":
	env_border_color.add_source_files(env.modules_sources, "border_color_osx.mm")
